# Generated by Django 3.2.4 on 2021-08-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('bug', models.CharField(max_length=50)),
                ('created', models.DateField()),
                ('assignee', models.CharField(max_length=50)),
                ('due', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=20)),
            ],
        ),
    ]
