# Generated by Django 3.2.4 on 2021-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210819_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('show_stopper', 'Show stopper'), ('major', 'Major'), ('minor', 'Minor')], default='major', max_length=20),
        ),
    ]
